/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.codice.imaging.nitf.nitfnetbeansfiletype;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import org.codice.imaging.cgm.AbstractElement;
import org.codice.imaging.cgm.CgmRenderer;
import org.openide.awt.ActionID;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Graphic Segment (CGM) View for the editor compartment.
 */
@TopComponent.Description(
        preferredID = "GraphicViewPane",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(
        mode = "editor",
        openAtStartup = false)
@ActionID(
        category = "Window",
        id = "org.codice.imaging.nitf.nitfnetbeansfiletype.GraphicViewPane")
@TopComponent.OpenActionRegistration(
        displayName = "CTL_GraphicSegmentView")
@NbBundle.Messages({
    "CTL_GraphicViewPane=Graphic Segment View"
})
public class GraphicViewPane extends TopComponent {

    private List<AbstractElement> commands;

    /**
     * Creates new form GraphicViewPane.
     */
    public GraphicViewPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // CSOFF: MagicNumber
    // CSOFF: WhitespaceAround
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // CSON: MagicNumber
    // CSON: WhitespaceAround

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    @Override
    public final void paint(final Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        CgmRenderer renderer = new CgmRenderer();
        renderer.setTargetImageGraphics((Graphics2D) g, getX(), getY());
        renderer.render(commands);
    }

    final void setCommands(final List<AbstractElement> cgmCommands) {
        commands = cgmCommands;
    }
}
