/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.codice.imaging.nitf.nitfnetbeansfiletype;

import org.openide.awt.ActionID;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Text Segment View for the editor compartment.
 */
@TopComponent.Description(
        preferredID = "TextSegmentView",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(
        mode = "editor",
        openAtStartup = false)
@ActionID(
        category = "Window",
        id = "org.codice.imaging.nitf.nitfnetbeansfiletype.TextSegmentViewer")
@TopComponent.OpenActionRegistration(
        displayName = "CTL_TextSegmentViewer")
@NbBundle.Messages({
    "CTL_TextSegmentViewer=Text Segment Viewer"
})
public class TextSegmentViewer extends TopComponent {

    // CSOFF: MagicNumber
    // CSOFF: WhitespaceAround
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setText(org.openide.util.NbBundle.getMessage(TextSegmentViewer.class, "TextSegmentViewer.textArea.text")); // NOI18N
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // CSON: MagicNumber
    // CSON: WhitespaceAround

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form TextSegmentViewer.
     */
    public TextSegmentViewer() {
        initComponents();
    }

    final void setText(final String text) {
        textArea.setText(text);
        textArea.setCaretPosition(0);
    }
}
