/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.codice.imaging.nitf.nitfnetbeansfiletype;

import javax.swing.tree.TreeModel;
import org.openide.awt.ActionID;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * TRE Tree-style View for the editor compartment.
 */
@TopComponent.Description(
        preferredID = "TreTreeView",
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(
        mode = "editor",
        openAtStartup = false)
@ActionID(
        category = "Window",
        id = "org.codice.imaging.nitf.nitfnetbeansfiletype.TreTreeViewerPane")
@TopComponent.OpenActionRegistration(
        displayName = "CTL_TreTreeViewerPane")
@NbBundle.Messages({
    "CTL_TreTreeViewerPane=TRE Viewer"
})
public class TreTreeViewerPane extends TopComponent {

    /**
     * Creates new form TreTreeViewerPane.
     */
    public TreTreeViewerPane() {
        initComponents();
    }

    // CSOFF: MagicNumber
    // CSOFF: WhitespaceAround
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treTree = new javax.swing.JTree();

        jScrollPane1.setViewportView(treTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // CSON: MagicNumber
    // CSON: WhitespaceAround

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treTree;
    // End of variables declaration//GEN-END:variables

    final void setTreeModel(final TreeModel model) {
        treTree.setModel(model);
    }
}
